default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>
  host: <%= ENV.fetch("DB_HOST") { 'db' } %>
  port: <%= ENV.fetch("DB_PORT") { '5432' } %>
  database: <%= ENV.fetch("DB_NAME") { 'db_local' } %>
  username: <%= ENV.fetch("DB_USER") { 'postgres' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'password' } %>
  connect_timeout: 5
  prepared_statements: false

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
